jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install requirements
        run: make adoptium

      - name: Clone OTP
        run: make otp

      - name: Clone patched oss-review-toolkit
        run: make ort

      - name: ORT Analyze
        run: make analyze
