name: SBOM Generation Test

on: workflow_dispatch

permissions:
  contents: read


jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      # - name: Checkout project
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'kikofernandez/otp'
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          run: >
            analyzer,
            scanner,
            advisor,
            reporter
          ort-cli-report-args: '-f SpdxDocument -O SpdxDocument=output.file.formats=JSON'
          ort-config-path: '.ort/config'
          vcs-url: 'https://github.com/kikofernandez/otp.git'
